import "../styles/globals.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import Footer from "../components/Footer";
import { AuthProvider } from "../lib/contexts/AuthContext";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Next.js + ORY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
      <Footer />
    </div>
  );
}

export default MyApp;
